title = "Electrolink config"

[server]
ip = "localhost"
port = 1883
keepalive = 60 # maximum period in seconds allowed between communications with the broker.

[thing]
# This name will be used to declare subscriptions
device_id = "weioA"
command_topic = "command"
reply_topic = "reply"
error_topic = "error"
